version: '3'
services:
  gateway:
    image: gateway
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    env_file:
      - ./services/gateway/.env
    depends_on:
      - storage
    restart: "no"

  storage:
    image: storage
    build:
      context: ./services/storage
      dockerfile: Dockerfile
    container_name: storage
    ports:
      - "4040:4040"
    env_file:
      - ./services/storage/.env
    restart: "no"