version: '3.9'
services:
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./services/gateway/.env
    volumes:
      - ./scripts/database/gateway/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

  postgres_history:
    image: postgres:15.3-alpine
    container_name: postgres_history
    ports:
      - "5433:5432"
    env_file:
      - ./services/history/.env
    volumes:
      - ./scripts/database/history/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

  rabbit:
    image: rabbitmq:3.11.17-management-alpine
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  storage:
    image: storage
    build:
      context: ./services/storage
      dockerfile: prod.Dockerfile
    container_name: storage
    ports:
      - "4040:4040"
    env_file:
      - ./services/storage/.env
    volumes:
      - ./services/storage/:/usr/src/app
    restart: "no"

  history:
    image: history
    build:
      context: ./services/history
      dockerfile: prod.Dockerfile
    container_name: history
    env_file:
      - ./services/history/.env
    volumes:
      - ./services/history/:/usr/src/app
    depends_on:
      - rabbit
      - postgres_history
    restart: "no"

  gateway:
    image: gateway
    build:
      context: ./services/gateway
      dockerfile: prod.Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    env_file:
      - ./services/gateway/.env
    volumes:
      - ./services/gateway/:/usr/src/app
    depends_on:
      - postgres
      - rabbit
      - storage
      - history
    restart: "no"