version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./services/gateway/.env
    volumes:
      - ./services/gateway/database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always

  storage:
    image: storage
    build:
      context: ./services/storage
      dockerfile: dev.Dockerfile
    container_name: storage
    ports:
      - "4040:4040"
    env_file:
      - ./services/storage/.env
    volumes:
      - ./services/storage/:/usr/src/app
    restart: "no"
    
  gateway:
    image: gateway
    build:
      context: ./services/gateway
      dockerfile: dev.Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    env_file:
      - ./services/gateway/.env
    volumes:
      - ./services/gateway/:/usr/src/app
    depends_on:
      - postgres
      - storage
    restart: "no"