// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.15.8
// source: pb/image_storage.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageStorageClient is the client API for ImageStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageStorageClient interface {
	GetImage(ctx context.Context, in *ImageStorageRequest, opts ...grpc.CallOption) (*ImageStorageResponse, error)
}

type imageStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewImageStorageClient(cc grpc.ClientConnInterface) ImageStorageClient {
	return &imageStorageClient{cc}
}

func (c *imageStorageClient) GetImage(ctx context.Context, in *ImageStorageRequest, opts ...grpc.CallOption) (*ImageStorageResponse, error) {
	out := new(ImageStorageResponse)
	err := c.cc.Invoke(ctx, "/storage.ImageStorage/GetImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImageStorageServer is the server API for ImageStorage service.
// All implementations must embed UnimplementedImageStorageServer
// for forward compatibility
type ImageStorageServer interface {
	GetImage(context.Context, *ImageStorageRequest) (*ImageStorageResponse, error)
	mustEmbedUnimplementedImageStorageServer()
}

// UnimplementedImageStorageServer must be embedded to have forward compatible implementations.
type UnimplementedImageStorageServer struct {
}

func (UnimplementedImageStorageServer) GetImage(context.Context, *ImageStorageRequest) (*ImageStorageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedImageStorageServer) mustEmbedUnimplementedImageStorageServer() {}

// UnsafeImageStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageStorageServer will
// result in compilation errors.
type UnsafeImageStorageServer interface {
	mustEmbedUnimplementedImageStorageServer()
}

func RegisterImageStorageServer(s grpc.ServiceRegistrar, srv ImageStorageServer) {
	s.RegisterService(&ImageStorage_ServiceDesc, srv)
}

func _ImageStorage_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImageStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageStorageServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/storage.ImageStorage/GetImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageStorageServer).GetImage(ctx, req.(*ImageStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ImageStorage_ServiceDesc is the grpc.ServiceDesc for ImageStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ImageStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.ImageStorage",
	HandlerType: (*ImageStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetImage",
			Handler:    _ImageStorage_GetImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/image_storage.proto",
}
