global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - "alertmanager:9093"

rule_files:
  - 'alert.rules'

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets:
          - "gateway:8080"